---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Reboot'
  shell: sleep 2 && shutdown now -r
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false



