language: c


matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - DEPLOY="true"
        - ARCH="armv7"

before_script:
  - cd src
  - sudo apt update -qq
  - sudo apt install -y -qq git
  - export BUILD_RELEASE_VERSION=`git describe --tags`
  - export BUILD_PACKAGE_NAME=helloworld-$BUILD_RELEASE_VERSION
  - export BUILD_PACKAGE_NAME_TGZ=$BUILD_PACKAGE_NAME.tgz

script:
  - "./buildit.sh"
    
deploy:
  provider: releases
  api_key:
    secure: gSWe5+GZ3d8kapgqrxqzEBjUynWleBxYRcbKmal05x3iAZAHuZMjFPfVWR/wWhGGw8c6Nj6/TzVcXZBnhG7xQwfILpSTOHbJ2+mLqWGgRUVnbi52B4ZMR6Ik0ZtEklYWrwUPhv4hxY6v01dIiV9SsK5qHt5hX/o3zEtfRfUmxU+02ksvIQGbOBj7ezMfWH19FAl7yJa0yJPc7bJNk22ft484JXVmIeFAWbUXn0P1aHsRcwUWCmS5h1GxPU20R+c6H2mjsJsIqs1QheWvG74Jca7Lywfv9nEy9LfRYJJp94uwl0k9NGOX3QOTaIhChoP5mlhuiNC5tdknfNmTFN9eM+5vOAquEKP/84Iw8t2UvycfvhnTVpCrBW+fj3KG9kKtRPXf8Kogtx6SDjsjY1dGeMAugb534/dPHxLvhnyMtUpbR31HdABK+Ft9JI7mplJjocg3W5wOqp1tKQo4igM8Y1n3Ra/A5Le66pLmhN75ruCiZ9qn/jNLr/xChKMK4kc+zHGmWfpSUiHgYYLAJ8TrbtsnzGeihOQYt4S1EwTgJLoifAicfU5Z3fUqx4yuvIoLcpocr4KBSKJ3DF29oc3e8w847dDCHtYkex2hduI47OY32cBZuLpqGbpyu9TxI5gyBRM4BsKd39TKb5+BevxO9FElgRdyMW9qMs8q8lKfLi8=
  file: "${BUILD_PACKAGE_NAME_TGZ}"
  skip_cleanup: true
  on:
    repo: jamesceri/cavycam
    tags: true
