---
- name: Copy auto start scripts
  copy: src='{{ files_path }}/auto_start' dest=/home/pi owner=pi group=pi mode=755

- name: Copy scripts directory
  copy: src='{{ files_path }}/scripts' dest=/home/pi owner=pi group=pi mode=755

- name: Copy lxde session autostart file
  copy: src='{{ generic_templates_path }}/pi_screens_lxsession_autostart'
        dest='/home/pi/.config/lxsession/LXDE-pi/autostart' owner=pi group=pi mode=644
